const SHORT_MOVIE_MAX_DURATION = 40;
const LIMIT_MOVIES_LARGE = 12;
const LIMIT_MOVIES_MEDIUM = 8;
const LIMIT_MOVIES_SMALL = 5;
const SCREEN_LARGE_MAX_WIDTH = 1280;
const SCREEN_MEDIUM_MAX_WIDTH = 850;
const SCREEN_SMALL_MAX_WIDTH = 767;
const ADDITIONAL_MOVIES_LARGE = 3;
const ADDITIONAL_MOVIES_MEDIUM = 2;
const ADDITIONAL_MOVIES_SMALL = 2;

export {
  SHORT_MOVIE_MAX_DURATION,
  SCREEN_LARGE_MAX_WIDTH,
  SCREEN_MEDIUM_MAX_WIDTH,
  SCREEN_SMALL_MAX_WIDTH,
  LIMIT_MOVIES_LARGE,
  LIMIT_MOVIES_MEDIUM,
  LIMIT_MOVIES_SMALL,
  ADDITIONAL_MOVIES_LARGE,
  ADDITIONAL_MOVIES_MEDIUM,
  ADDITIONAL_MOVIES_SMALL,
};
